spring:
  profiles:
    active: dev


---

server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microservice-config-client-dev


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/



---
server:
  port: 8205
spring:
  profiles: test
  application:
    name: microservice-config-client-test


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

